---
title: "EASD:  Observable Node Relationships"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(shiny)
library(shinyjs)
library(PNetica)
library(googlesheets4)
```

```{r LoadModel, include=FALSE}
sess <- RNetica::NeticaSession() # Add the license key here
RNetica::startSession(sess)
sheetID <- "https://docs.google.com/spreadsheets/d/1r0h_wPKPa8qQzbpI_JT-T2ic4N8l9oypEG0AeIuaBn8/edit?usp=sharing"
sheetIDnew <- "1UMBMlebAj8XFnm4ptE3k5V34Lx-I32KYVIvQpr7Paog"
googlesheets4::gs4_deauth()
netman <- read_sheet(sheetID,"Nets")
knitr::kable(netman)
Nethouse <- PNetica::BNWarehouse(netman,sess)
nodeman <- read_sheet(sheetID,"Nodes")
Nodehouse <- PNetica::NNWarehouse(nodeman,sess)
omega <- as.data.frame(read_sheet(sheetID,"Omega"))
CM <- WarehouseSupply(Nethouse,"EASD")
CM1 <- Omega2Pnet(omega,CM,Nodehouse,override=TRUE)
Q1 <- as.data.frame(read_sheet(sheetID,"Q"))
try(Qmat2Pnet(Q1,Nethouse,Nodehouse))
```

```{r kludge, include=FALSE}
EM1 <- WarehouseSupply(Nethouse,"DK1_SP2")
Rel <- PnetFindNode(EM1,"Relationships")
# PnodeAlphas(Rel) <- list(1,1)
# PnodeBetas(Rel) <- 
#   list(Full=c(CP2=.5,DK1=0),Partial=c(CP2=-.5,DK1=0))
BuildTable(Rel)
```
Note that there are two tabs on the input panel, one for the transition from `No Credit` to `Partial Credit` and one for the transitions from `Partial Credit` to `Full Credit`.


<style>iframe.shiny-frame{height: 2000px}</style>
```{r gadget, echo=FALSE}
gadget3 <- MakeDPCGadget(Rel)
shiny::shinyApp(gadget3$ui,gadget3$server, options(height=2000))
```
